import type { AthletePayload } from './components/AthleteDetail.js';
import realData from './fixtures/attended-player.json' with { type: 'json' };

const real = realData as unknown as AthletePayload;

const georgeKirby: AthletePayload = {
  player: {
    id: 4118,
    mlb_stats_id: 669923,
    full_name: 'George Kirby',
    primary_position: 'RHP',
    primary_number: '68',
    bats: 'R',
    throws: 'R',
    debut_date: '2022-05-08',
    birth_country: 'USA',
    photo_silo: null,
    photo_full: {
      cdn_url: 'https://cdn.rewind.rest/attending/player_full/4118',
      url: null,
      thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
      dominant_color: '#0c2c56',
      accent_color: '#c4ced4',
    },
    league: 'mlb',
    team: {
      id: 136,
      name: 'Seattle Mariners',
      abbreviation: 'SEA',
      league: 'mlb',
      primary_color: '#0c2c56',
      logo: {
        cdn_url: 'https://cdn.rewind.rest/attending/mlb_team_logo/136',
        url: null,
        thumbhash: null,
        dominant_color: '#0c2c56',
        accent_color: '#c4ced4',
      },
    },
  },
  supported: true,
  season_stats: {
    season: 2026,
    fetched_at: '2026-04-27T15:00:00Z',
    cache_hit: true,
    hitter: null,
    pitcher: {
      games_played: 5,
      games_started: 5,
      ip: '32.0',
      bf: 124,
      h: 28,
      r: 9,
      er: 9,
      bb: 6,
      k: 31,
      hr: 3,
      era: '2.53',
      whip: '1.06',
      decisions: { w: 3, l: 1, sv: 0, hld: 0, bs: 0 },
    },
  },
  attended_summary: {
    games_attended: 10,
    games_with_box_score: 10,
    wins: 6,
    losses: 4,
    hitter: null,
    pitcher: {
      ip: '65.1',
      bf: 238,
      h: 50,
      r: 26,
      er: 24,
      bb: 12,
      k: 71,
      era: '3.31',
      whip: '1.10',
      decisions: { w: 4, l: 3, sv: 0, hld: 0, bs: 0 },
      games_played: 10,
    },
  },
  attended_appearances: [
    {
      event_id: 9101,
      event_date: '2026-04-19T19:10:00Z',
      title: 'SEA vs ATL',
      is_home: true,
      batting_line: null,
      pitching_line: { ip: '7.0', h: 4, er: 1, bb: 1, k: 9 },
      decision: 'W',
      notable: true,
      notable_reasons: ['win'],
    },
    {
      event_id: 9102,
      event_date: '2026-04-04T19:10:00Z',
      title: 'SEA vs OAK',
      is_home: true,
      batting_line: null,
      pitching_line: { ip: '6.1', h: 7, er: 3, bb: 2, k: 7 },
      decision: 'L',
      notable: false,
      notable_reasons: [],
    },
    {
      event_id: 9103,
      event_date: '2025-09-21T19:10:00Z',
      title: 'SEA vs LAA',
      is_home: true,
      batting_line: null,
      pitching_line: { ip: '8.0', h: 3, er: 0, bb: 0, k: 11 },
      decision: 'W',
      notable: true,
      notable_reasons: ['win', '11 K'],
    },
  ],
  attended_appearance_count: 10,
};

const nflPlayerUnsupported: AthletePayload = {
  player: {
    id: 5500,
    mlb_stats_id: null,
    full_name: 'D.K. Metcalf',
    primary_position: 'WR',
    primary_number: '14',
    bats: null,
    throws: null,
    debut_date: null,
    birth_country: 'USA',
    photo_silo: null,
    photo_full: null,
    league: 'nfl',
    team: null,
  },
  supported: false,
  season_stats: null,
  attended_summary: {
    games_attended: 4,
    games_with_box_score: 0,
    wins: 2,
    losses: 2,
    hitter: null,
    pitcher: null,
  },
  attended_appearances: [
    {
      event_id: 9201,
      event_date: '2026-01-05T21:30:00Z',
      title: 'SEA at NYJ',
      is_home: false,
      batting_line: null,
      pitching_line: null,
      decision: null,
      notable: false,
      notable_reasons: [],
    },
    {
      event_id: 9202,
      event_date: '2025-12-15T21:25:00Z',
      title: 'SEA vs GB',
      is_home: true,
      batting_line: null,
      pitching_line: null,
      decision: null,
      notable: false,
      notable_reasons: [],
    },
  ],
  attended_appearance_count: 4,
};

export const fixtures: Record<string, AthletePayload> = {
  default: real,
  pitcher: georgeKirby,
  'unsupported-nfl': nflPlayerUnsupported,
};
